// Touchstone config — generated by `touchstone init`. This is the one file you maintain.
export default {
  touchstoneVersion: 1,
  app: { useRunningServer: true, healthPath: "/" },
  baseURL: process.env.QA_BASE_URL || "", // ← set your target here (or export QA_BASE_URL); empty = not configured, a run will say so
  // Any @playwright/test device name. Full list: node -e "console.log(Object.keys(require('@playwright/test').devices).join('\n'))"
  devices: process.env.QA_DEVICES?.split(',').map((d) => d.trim()) ?? ["Desktop Chrome"],
  // gallery: { routes: ['/'], themes: ['light', 'dark'], themeStorageKey: '<your theme localStorage key>' }, // for /visual-qa + @visual baselines

  // Evidence captured automatically (zero cost on green runs). Each mode: 'off' | 'on-failure' | 'always'.
  capture: {
    appLogs: 'off',          // remote target — no local app process to log
    screenshot: "on-failure",   // page screenshot (browser tests)
    console: "on-failure",      // browser console — tune via consoleLevels: ['error','warning']
    pageErrors: "on-failure",   // uncaught exceptions in the page
    network: "off",             // request log — opt-in (set networkMaxEntries to cap size)
    systemMetrics: "on-failure", // portable cpu / mem / load snapshot
    // dbCollections: ['users', 'orders'], // Mongo: snapshot these collections on failure
    // browserMetrics: 'on-failure',       // CDP heap / DOM nodes / web-vitals (Chromium only)
    // osDeep: 'off',                       // deep OS metrics via shell-outs (vm_stat/top/wevtutil) — opt-in
  },
  readOnly: true, // live target — refuse mutating HTTP
  // Analyze the captured evidence for findings the assertions missed (deterministic, no AI). Drop your own in app-qa/analyzers/.
  analyze: { mode: "on-failure" }, // 'on-failure' (mine failures) | 'always' (also catch passed-but-dirty on green)

  safety: {
    requireOptIn: true,
    testDbPattern: /(_|-)(test|qa|ci)$/i,
    testBucketPattern: /(^|[._-])(test|qa|ci|dev)([._-]|$)/i,
    prod: { dbNames: [], bucketNames: [], uriHostDenylist: [] },
  },
};
